"""initial schema

Revision ID: 081eef6a8820
Revises:
Create Date: 2026-04-18 16:03:05.080749

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "081eef6a8820"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("mime_type", sa.Text(), nullable=False),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("parse_duration_ms", sa.Integer(), nullable=True),
        sa.Column("embed_duration_ms", sa.Integer(), nullable=True),
        sa.Column(
            "uploaded_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("parsed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'parsing', 'chunking', 'embedding', 'ready', 'failed')",
            name="documents_status_check",
        ),
        sa.CheckConstraint("file_size_bytes >= 0", name="documents_file_size_bytes_check"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_documents_tenant_content_hash", "documents", ["tenant_id", "content_hash"], unique=False
    )
    op.create_index("ix_documents_tenant_id_id", "documents", ["tenant_id", "id"], unique=False)
    op.create_index(
        "ix_documents_tenant_id_status", "documents", ["tenant_id", "status"], unique=False
    )
    op.create_table(
        "chunks",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.Column("char_end", sa.Integer(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint("char_end > char_start", name="chunks_char_end_check"),
        sa.CheckConstraint("char_start >= 0", name="chunks_char_start_check"),
        sa.CheckConstraint("token_count > 0", name="chunks_token_count_check"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "chunk_index", name="chunks_document_chunk_index_key"),
    )
    op.create_index(
        "ix_chunks_tenant_document", "chunks", ["tenant_id", "document_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_chunks_tenant_document", table_name="chunks")
    op.drop_table("chunks")
    op.drop_index("ix_documents_tenant_id_status", table_name="documents")
    op.drop_index("ix_documents_tenant_id_id", table_name="documents")
    op.drop_index("ix_documents_tenant_content_hash", table_name="documents")
    op.drop_table("documents")
    op.drop_table("tenants")
    # ### end Alembic commands ###
