"""tenant_llm_configs

Revision ID: ffa2b6ed122c
Revises: 081eef6a8820
Create Date: 2026-05-04 15:35:19.708604

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "ffa2b6ed122c"
down_revision: str | None = "081eef6a8820"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenant_llm_configs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model_name", sa.Text(), nullable=False),
        sa.Column("base_url", sa.Text(), nullable=True),
        sa.Column("api_key_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("api_key_last4", sa.String(length=4), server_default="", nullable=False),
        sa.Column("test_status", sa.String(length=16), server_default="untested", nullable=False),
        sa.Column("test_error", sa.Text(), nullable=True),
        sa.Column("tested_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "(provider = 'ollama')"
            " OR ("
            " api_key_encrypted IS NOT NULL"
            " AND length(api_key_encrypted) >= 80"
            " AND length(api_key_last4) = 4"
            ")",
            name="ck_tenant_llm_configs_api_key_present_when_required",
        ),
        sa.CheckConstraint(
            "provider IN ("
            "'anthropic', 'openai', 'google', 'mistral', 'openai_compatible', 'ollama'"
            ")",
            name="ck_tenant_llm_configs_provider",
        ),
        sa.CheckConstraint(
            "test_status IN ('untested', 'passed', 'failed')",
            name="ck_tenant_llm_configs_test_status",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_tenant_llm_configs_tenant", "tenant_llm_configs", ["tenant_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tenant_llm_configs_tenant", table_name="tenant_llm_configs")
    op.drop_table("tenant_llm_configs")
    # ### end Alembic commands ###
